### PR TITLE
Make the header files easier to compile.	

### PR DESCRIPTION
**Pull request by vinjn**
Prefer local includes to absolute includes.

### CODE REVIEW

**Comment by ZahlGraf** [comment]
Thanks for the contribution. As I wrote in my line comment I will merge the changes for the local headers but not for the external includes to dependencies. I will do it today evening.

**Comment by vinjn** [comment]
By the way, what kind of project are you using Irrlicht for?

**Comment by ZahlGraf** [comment]
Thanks for changing the pull-request :+1: 

At the moment I don't have a specific big project with Irrlicht. In the past I realized several small projects mostly for learning reasons... for example writing some shaders or build up nice 3D scenes.
In future I want to create a more complex program, that's why I was looking for a nice GUI.

However there are not so much GUI systems for Irrlicht available... you can use the build-in Irrlicht GUI, but I don't like the style. Or you can use CEGUI, but this library has a lot of dependencies and I also don't like the style of the standard themes delivered with CEGUI.

Then I found IMGUI and it is exactly what I was looking for: Simple, modern look-and-feel and without much dependencies. Thus I created IrrIMGUI to integrate it later in my projects.
Maybe I will try to create a small and simple game with it... let's see :)

**Comment by vinjn** [comment]
:)

**Pull request merged**
